### ISSUE TITLE
Reach out to Aaron Lowe for Public Easement data

### ISSUE THREAD

**Issue by rbvea** [CodeforHawaii/ACLU#11]
Get shapefiles for Public Easements

**Comment by tiktnarg** [comment]
7/21/17, spoke with Aaron. He said the one-pager was circulated internally at DFAW (Dept of Forestry and Wildlife), of which he is acting director. 

A challenge: He said they have deep concern about the project, their office was created to document over 2000 pathways on public land on O‘ahu alone, but they only share info publicly for about 123 of them, because they are fragile ecosystems or have vulnerable cultural artifacts. He said easements will be especially hard because many have unclear status, or contested status. I reassured him that we are not looking to drive masses of tourists to less known trails, and that we want to be extremely sensitive to the host culture and ecological concerns, that including DFAW as a project stakeholder is important to us. Also, he is transitioning out as the acting Director, ad will go back to being the trail manager for O‘ahu, so leadership for the project at DFAW is likely to transition. I let him know our timeframe for public launch as early 2019, so we would be happy to connect and work with whomever is in the top seat.  (Lots of internal bridge building to do here). 

He also said that the shapefiles for all of the public trails statewide can be gotten from the City and County GIS Office of Planning, and we are welcome to them for the project. http://planning.hawaii.gov/gis/download-gis-data/

His contact info is: aaron.lowe@hawaii.gov
Division of Forestry and Wildlife
Na Ala Hele Trail and Access Program
Department of Land and Natural Resources
1151 Punchbowl Street
Room 325, Kalanimoku Building
Honolulu, HI 96813
Phone: (808) 587-4175
