### ISSUE TITLE
Finalize taxonomy and priority areas for data sources

### ISSUE THREAD

**Issue by rbvea** [CodeforHawaii/ACLU#13]

**Comment by mckaydavis** [comment]
Please fill out Column C (Priority) in this Google Sheet:
https://docs.google.com/spreadsheets/d/1eDXV0qamY_5pcfe0SZbqs2PQXR_yJUs0-liX7sJo3wE/

**Comment by tiktnarg** [comment]
Aloha all, I went thru and ranked them here is the logic I used:

Three main "zones" for the project: URBAN, MAUKA, MAKAI.

I prioritized according to where we seem to hear about the most conflict in
public access: URBAN as top priority, then MAUKA (trails), then MAKAI
(harbors, coastline, water). I left Military as a lower priority since they
are generally really good at fencing and signing their areas - except for
military holdings in high traffic urban areas (specifically Fort DeRussy).
I hope that makes sense. Also added in some jurisdictional information we
may need to find out (DOCARE, HPD).
